### PR TITLE
Merge/upstream 20210824

### PR DESCRIPTION
**Pull request by fredoh9**
master tip as of today,
754c696a rawmidi: Use the standard types for snd_rawmidi_framing_tstamp_t definition

### CODE REVIEW

**Comment by plbossart** [comment]
Not sure what the conflicts are nor what are you trying to do @fredoh9 ?

**Comment by fredoh9** [comment]
> Not sure what the conflicts are nor what are you trying to do @fredoh9 ?

Hum not sure why I have the conflicts.

I'm trying to update our docker image. Need to update alsa-lib/alsa-uilts.
https://github.com/thesofproject/sof/blob/main/scripts/docker_build/sof_builder/Dockerfile

**Comment by plbossart** [comment]
why not just do a git push --force, or directly use upstream?

**Comment by fredoh9** [comment]
We can use upstream directly also. I think we had build issues with upstream master. May be that's why we started to use our own repo.

I don't think I have the permission to push --force to master. Can @plbossart @ranj063 @lgirdwood push --force with alsa-lib master today? And I need an alsa-utils update also.

**Comment by plbossart** [comment]
well maybe we can check first why we need this?

Do we actually want to build from the latest and greatest alsa-lib/alsa-utils, or from the last version? And in the latter case, didn't we have some packages ready that @libinyang generated?

It seems that we are creating too much work for ourselves?

**Comment by ranj063** [comment]
> well maybe we can check first why we need this?
> 
> Do we actually want to build from the latest and greatest alsa-lib/alsa-utils, or from the last version? And in the latter case, didn't we have some packages ready that @libinyang generated?
> 
> It seems that we are creating too much work for ourselves?

@plbossart I asked to update alsa-utils to the latest upstream because Jaroslav merged our last PR yesterday and I need it to add the build support for topology2 in SOF

**Comment by plbossart** [comment]
> @plbossart I asked to update alsa-utils to the latest upstream because Jaroslav merged our last PR yesterday and I need it to add the build support for topology2 in SOF

ok, I forced-push the master branch for alsa-lib and alsa-utils, please double-check you have everything you need.

**Comment by aiChaoSONG** [comment]
@fredoh9 Maybe this is the reason you got build failure, https://github.com/alsa-project/alsa-lib/issues/172

**Pull request closed without merging**
